# Python 3 Notebook

# =============  PART - 1 ==================

# Basics: 

* Data types
    * Numbers
    * Strings
    * Printing
    * Lists
    * Dictionaries
    * Booleans
    * Tuples 
    * Sets
* Comparison Operators
* if,elif, else Statements
* for Loops
* while Loops
* range()
* list comprehension
* functions
* lambda expressions
* map and filter
* methods
____

## Data types

### Numbers

In [1]:
1 + 1

2

In [4]:
1 * 3

3

In [7]:
1 / 2

0.5

In [8]:
2 ** 4

16

In [9]:
4 % 2

0

In [10]:
5 % 2

1

In [11]:
(2 + 3) * (5 + 5)

50

### Variable Assignment

In [13]:
# Can not start with number or special characters
name_of_var = 2
name_of_var

2

In [14]:
x = 2
y = 3

In [15]:
z = x + y

In [16]:
z

5

### Strings

In [17]:
'single quotes'

'single quotes'

In [19]:
"double quotes"

'double quotes'

In [20]:
" wrap lot's of other quotes"

" wrap lot's of other quotes"

### Printing

In [21]:
x = 'hello'

In [22]:
x

'hello'

In [23]:
print(x)

hello


In [25]:
num = 12
name = 'Sam'

In [26]:
print('My number is: {one}, and my name is: {two}'.format(one=num,two=name))

My number is: 12, and my name is: Sam


In [27]:
print('My number is: {}, and my name is: {}'.format(num,name))

My number is: 12, and my name is: Sam


## Lists
index starts with 0, unlike 1 in **R**

In [28]:
[1,2,3]

[1, 2, 3]

In [29]:
['hi',1,[1,2]]

['hi', 1, [1, 2]]

In [30]:
my_list = ['a','b','c']

**appending an element to the list**

In [31]:
my_list.append('d')

In [32]:
my_list

['a', 'b', 'c', 'd']

**Subsetting**

In [34]:
my_list[0]

'a'

In [35]:
my_list[1]

'b'

In [33]:
my_list[1:]

['b', 'c', 'd']

In [36]:
my_list[:1]

['a']

**Replacement**

In [37]:
my_list[0] = 'NEW'

In [38]:
my_list

['NEW', 'b', 'c', 'd']

**Nesting**

In [18]:
nest = [1,2,3,[4,5,['target']]]

In [19]:
nest[3]

[4, 5, ['target']]

In [20]:
nest[3][2]

['target']

In [21]:
nest[3][2][0]

'target'

## Dictionaries
**Key value pairs**

In [39]:
d = {'key1':'item1','key2':'item2'}

In [40]:
d

{'key1': 'item1', 'key2': 'item2'}

In [24]:
d['key1']

'item1'

## Booleans

In [25]:
True

True

In [41]:
False

False

## Tuples 
**Like list but immutable**

In [42]:
t = (1,2,3,4)

In [43]:
t

(1, 2, 3, 4)

In [44]:
t[0]

1

**Item reassignment is not possible in Tuples**

In [45]:
t[0] = 6

TypeError: 'tuple' object does not support item assignment

## Sets
**Unique elements**

In [46]:
{1,2,3}

{1, 2, 3}

In [47]:
{6,1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}

{1, 2, 3, 6}

## Comparison Operators

In [52]:
1 > 2

False

In [54]:
1 < 2

True

In [49]:
1 >= 1

True

In [50]:
1 <= 4

True

In [49]:
1 == 1

True

In [50]:
'hi' == 'bye'

False

## Logic Operators

In [55]:
(1 > 2) and (2 < 3)

False

In [56]:
(1 > 2) or (2 < 3)

True

In [57]:
(1 == 2) or (2 == 3) or (4 == 4)

True

## if,elif, else Statements

In [58]:
if 1 < 2:
    print('Yep!')

Yep!


In [59]:
if 1 < 2:
    print('yep!')

yep!


In [60]:
if 1 < 2:
    print('first')
else:
    print('last')

first


In [61]:
if 1 > 2:
    print('first')
else:
    print('last')

last


In [45]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('Last')

middle


## "for" Loops

In [63]:
seq = [1,2,3,4,5]

In [66]:
for item in seq:
    print(item)

1
2
3
4
5


In [65]:
for item in seq:
    print('Yep')

Yep
Yep
Yep
Yep
Yep


In [68]:
for random in seq:
    print(random*random)

1
4
9
16
25


## while Loops

In [69]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i+1

i is: 1
i is: 2
i is: 3
i is: 4


## range()

In [70]:
range(5)

range(0, 5)

In [71]:
for i in range(5):
    print(i)

0
1
2
3
4


In [74]:
list(range(5))

[0, 1, 2, 3, 4]

In [75]:
tuple(range(5))

(0, 1, 2, 3, 4)

In [77]:
set(range(5))

{0, 1, 2, 3, 4}

## list comprehension

In [78]:
x = [1,2,3,4]

In [79]:
out = []
for item in x:
    out.append(item**2)
print(out)

[1, 4, 9, 16]


**Short and Sweet**

In [56]:
[item**2 for item in x]

[1, 4, 9, 16]

## functions

In [80]:
def my_func(param1='default'):
    """
    Docstring goes here.
    """
    print(param1)

In [58]:
my_func

<function __main__.my_func>

In [59]:
my_func()

default


In [60]:
my_func('new param')

new param


In [61]:
my_func(param1='new param')

new param


In [82]:
def square(x):
    return x**2

In [83]:
out = square(2)

In [84]:
print(out)

4


## lambda expressions

In [88]:
def times2(var):
    return var*2

In [71]:
times2(2)

4

In [99]:
lambda var: var*2

<function __main__.<lambda>>

## map and filter

In [86]:
seq = [1,2,3,4,5]

In [89]:
map(times2,seq)

In [90]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [75]:
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [76]:
filter(lambda item: item%2 == 0,seq)

In [91]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

## methods

In [92]:
st = 'hello my name is Sam'

In [93]:
st.lower()

'hello my name is sam'

In [113]:
st.upper()

'HELLO MY NAME IS SAM'

In [103]:
st.split()

['hello', 'my', 'name', 'is', 'Sam']

In [104]:
tweet = 'Go Sports! #Sports'

In [106]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [107]:
tweet.split('#')[1]

'Sports'

In [94]:
d

{'key1': 'item1', 'key2': 'item2'}

In [95]:
d.keys()

dict_keys(['key1', 'key2'])

In [80]:
d.items()

dict_items([('key1', 'item1'), ('key2', 'item2')])

In [81]:
lst = [1,2,3]

In [82]:
lst.pop()

3

In [108]:
lst

[1, 2]

In [83]:
'x' in [1,2,3]

False

In [84]:
'x' in ['x','y','z']

True



# =====================  PART - 2 ========================

# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

### Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: **vectors,arrays,matrices, and number generation**. Let's start by discussing arrays.

# 2.1 Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column)


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval. (same as seq() method in R)

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### zeros and ones

Generate arrays of zeros or ones

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [16]:
np.linspace(0,10,3)
# seq(0, 10, length.out = 3) as used in R 

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [37]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [19]:
np.random.rand(2)

array([0.4168594 , 0.16422106])

In [18]:
np.random.rand(5,5)

array([[0.33371118, 0.34319282, 0.72743529, 0.34876676, 0.96682784],
       [0.50934798, 0.55741392, 0.44898413, 0.9268689 , 0.99626748],
       [0.47303299, 0.22070455, 0.59786895, 0.47015036, 0.0581506 ],
       [0.14515479, 0.48025655, 0.25238249, 0.26587709, 0.83500126],
       [0.29003626, 0.47919666, 0.73504955, 0.25851799, 0.89794887]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(2)

array([-0.94830645,  0.80847746])

In [20]:
np.random.randn(5,5)

array([[ 0.56747593, -0.24927514, -0.19239578, -1.19321264, -2.16080915],
       [ 0.94410005,  0.38345592, -0.71832965,  0.22537232,  2.15568259],
       [-0.83998786,  0.23741113, -0.09165337,  0.48479975,  1.45805003],
       [-1.39779514,  0.1162762 ,  0.17916911,  0.23645086, -1.12615982],
       [ 1.72891056, -0.23289678,  0.75540383, -0.28040264,  0.35345829]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [26]:
np.random.randint(1,100)

8

In [30]:
np.random.randint(1,100,10)

array([13, 69, 34, 42, 25,  8, 91, 13, 48, 81])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [39]:
arr = np.arange(25)
ranarr = np.random.randint(0,25,10)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr

array([16, 11, 19, 18, 22,  6,  2, 12,  4, 15])

## Reshape
Returns an array containing the same data with a new shape.

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
ranarr.reshape(5,2)

array([[16, 11],
       [19, 18],
       [22,  6],
       [ 2, 12],
       [ 4, 15]])

In [47]:
ranarr

array([16, 11, 19, 18, 22,  6,  2, 12,  4, 15])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [59]:
ranarr

array([15,  4, 10, 23, 24, 24, 22, 23, 20,  9])

In [49]:
ranarr.max()
# max element

22

In [48]:
ranarr.argmax()
# argument to max element

4

In [62]:
ranarr.min()

4

In [63]:
ranarr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [56]:
# Vector
arr.shape

(25,)

In [60]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [62]:
arr.reshape(1,25).shape

(1, 25)

In [63]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### dtype

You can also grab the data type of the object in the array:

In [66]:
arr.dtype

dtype('int64')

# 2.2 NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic.(Same as in R)

In [67]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [70]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
# Warning on division by zero, but not an error!
# Just replaced with "nan"
arr/arr

/home/ideaplunge/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
# Also warning, but not an error instead infinity
1/arr

/home/ideaplunge/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [77]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [79]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
np.max(arr) #same as arr.max()

9

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [80]:
np.log(arr)

/home/ideaplunge/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# 2.3 NumPy Indexing and Selection

how to select elements or groups of elements from an array.

In [82]:
import numpy as np

In [136]:
#Creating sample array
arr = np.arange(0,11)

In [137]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [150]:
#Get a value at an index
arr[8]

8

In [151]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [152]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [153]:
# index starts at 0; dont forget that
arr[:4]

array([0, 1, 2, 3])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [154]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [155]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

changing the slice would also change the original array. (unlike R - this doesnt happen there)

In [158]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [98]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### copy
Data is not copied, it's a view of the original array! This avoids memory problems!

In [159]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

changes in copy wont affect the original array

In [160]:
arr_copy[:] = 0
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [161]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. comma notation is recommended for clarity.

In [162]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [163]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [115]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [119]:
# Getting individual element value
arr_2d[1,0]

20

In [130]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [117]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [148]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [171]:
# changing same as R 
arr_2d[2,:] = 0
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [ 0,  0,  0]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [173]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [185]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

10

In [186]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following (notice double brackets)

In [188]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [189]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size.

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [190]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [191]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [192]:
bool_arr = arr>4

In [193]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [194]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [195]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])



# =====================  PART - 3 ========================

# Pandas


# 3.1 Series

The first main data type we will learn about for pandas is the Series data type. Let's import Pandas and explore the Series object.

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

Let's explore this concept through some examples:

In [196]:
import numpy as np
import pandas as pd

### Creating a Series

You can convert a list,numpy array, or dictionary to a Series:

In [197]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

** Using Lists**

In [198]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [200]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [201]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

** NumPy Arrays **

In [205]:
arr

array([10, 20, 30])

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [202]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

** Dictionary**

In [204]:
d

{'a': 10, 'b': 20, 'c': 30}

In [203]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types:

In [8]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [210]:
# Even functions (although unlikely that you will use this)
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

## Using an Index

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like a hash table or dictionary).

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [211]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                                   

In [212]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [208]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])                                   

In [209]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [14]:
ser1['USA']

1

Operations are then also done based off of index:

In [213]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

Let's stop here for now and move on to DataFrames, which will expand on the concept of Series!