# Python 3 Notebook

# =============  PART - 1 ==================

# Basics: 

* Data types
    * Numbers
    * Strings
    * Printing
    * Lists
    * Dictionaries
    * Booleans
    * Tuples 
    * Sets
* Comparison Operators
* if,elif, else Statements
* for Loops
* while Loops
* range()
* list comprehension
* functions
* lambda expressions
* map and filter
* methods
____

## Data types

### Numbers

In [1]:
1 + 1

2

In [4]:
1 * 3

3

In [7]:
1 / 2

0.5

In [8]:
2 ** 4

16

In [9]:
4 % 2

0

In [10]:
5 % 2

1

In [11]:
(2 + 3) * (5 + 5)

50

### Variable Assignment

In [13]:
# Can not start with number or special characters
name_of_var = 2
name_of_var

2

In [14]:
x = 2
y = 3

In [15]:
z = x + y

In [16]:
z

5

### Strings

In [17]:
'single quotes'

'single quotes'

In [19]:
"double quotes"

'double quotes'

In [20]:
" wrap lot's of other quotes"

" wrap lot's of other quotes"

### Printing

In [21]:
x = 'hello'

In [22]:
x

'hello'

In [23]:
print(x)

hello


In [25]:
num = 12
name = 'Sam'

In [26]:
print('My number is: {one}, and my name is: {two}'.format(one=num,two=name))

My number is: 12, and my name is: Sam


In [27]:
print('My number is: {}, and my name is: {}'.format(num,name))

My number is: 12, and my name is: Sam


## Lists
index starts with 0, unlike 1 in **R**

In [28]:
[1,2,3]

[1, 2, 3]

In [29]:
['hi',1,[1,2]]

['hi', 1, [1, 2]]

In [30]:
my_list = ['a','b','c']

**appending an element to the list**

In [31]:
my_list.append('d')

In [32]:
my_list

['a', 'b', 'c', 'd']

**Subsetting**

In [34]:
my_list[0]

'a'

In [35]:
my_list[1]

'b'

In [33]:
my_list[1:]

['b', 'c', 'd']

In [36]:
my_list[:1]

['a']

**Replacement**

In [37]:
my_list[0] = 'NEW'

In [38]:
my_list

['NEW', 'b', 'c', 'd']

**Nesting**

In [18]:
nest = [1,2,3,[4,5,['target']]]

In [19]:
nest[3]

[4, 5, ['target']]

In [20]:
nest[3][2]

['target']

In [21]:
nest[3][2][0]

'target'

## Dictionaries
**Key value pairs**

In [39]:
d = {'key1':'item1','key2':'item2'}

In [40]:
d

{'key1': 'item1', 'key2': 'item2'}

In [24]:
d['key1']

'item1'

## Booleans

In [25]:
True

True

In [41]:
False

False

## Tuples 
**Like list but immutable**

In [42]:
t = (1,2,3,4)

In [43]:
t

(1, 2, 3, 4)

In [44]:
t[0]

1

**Item reassignment is not possible in Tuples**

In [45]:
t[0] = 6

TypeError: 'tuple' object does not support item assignment

## Sets
**Unique elements**

In [46]:
{1,2,3}

{1, 2, 3}

In [47]:
{6,1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}

{1, 2, 3, 6}

## Comparison Operators

In [52]:
1 > 2

False

In [54]:
1 < 2

True

In [49]:
1 >= 1

True

In [50]:
1 <= 4

True

In [49]:
1 == 1

True

In [50]:
'hi' == 'bye'

False

## Logic Operators

In [55]:
(1 > 2) and (2 < 3)

False

In [56]:
(1 > 2) or (2 < 3)

True

In [57]:
(1 == 2) or (2 == 3) or (4 == 4)

True

## if,elif, else Statements

In [58]:
if 1 < 2:
    print('Yep!')

Yep!


In [59]:
if 1 < 2:
    print('yep!')

yep!


In [60]:
if 1 < 2:
    print('first')
else:
    print('last')

first


In [61]:
if 1 > 2:
    print('first')
else:
    print('last')

last


In [45]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('Last')

middle


## "for" Loops

In [63]:
seq = [1,2,3,4,5]

In [66]:
for item in seq:
    print(item)

1
2
3
4
5


In [65]:
for item in seq:
    print('Yep')

Yep
Yep
Yep
Yep
Yep


In [68]:
for random in seq:
    print(random*random)

1
4
9
16
25


## while Loops

In [69]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i+1

i is: 1
i is: 2
i is: 3
i is: 4


## range()

In [70]:
range(5)

range(0, 5)

In [71]:
for i in range(5):
    print(i)

0
1
2
3
4


In [74]:
list(range(5))

[0, 1, 2, 3, 4]

In [75]:
tuple(range(5))

(0, 1, 2, 3, 4)

In [77]:
set(range(5))

{0, 1, 2, 3, 4}

## list comprehension

In [78]:
x = [1,2,3,4]

In [79]:
out = []
for item in x:
    out.append(item**2)
print(out)

[1, 4, 9, 16]


**Short and Sweet**

In [56]:
[item**2 for item in x]

[1, 4, 9, 16]

## functions

In [80]:
def my_func(param1='default'):
    """
    Docstring goes here.
    """
    print(param1)

In [58]:
my_func

<function __main__.my_func>

In [59]:
my_func()

default


In [60]:
my_func('new param')

new param


In [61]:
my_func(param1='new param')

new param


In [82]:
def square(x):
    return x**2

In [83]:
out = square(2)

In [84]:
print(out)

4


## lambda expressions

In [88]:
def times2(var):
    return var*2

In [71]:
times2(2)

4

In [99]:
lambda var: var*2

<function __main__.<lambda>>

## map and filter

In [86]:
seq = [1,2,3,4,5]

In [89]:
map(times2,seq)

In [90]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [75]:
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [76]:
filter(lambda item: item%2 == 0,seq)

In [91]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

## methods

In [92]:
st = 'hello my name is Sam'

In [93]:
st.lower()

'hello my name is sam'

In [113]:
st.upper()

'HELLO MY NAME IS SAM'

In [103]:
st.split()

['hello', 'my', 'name', 'is', 'Sam']

In [104]:
tweet = 'Go Sports! #Sports'

In [106]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [107]:
tweet.split('#')[1]

'Sports'

In [94]:
d

{'key1': 'item1', 'key2': 'item2'}

In [95]:
d.keys()

dict_keys(['key1', 'key2'])

In [80]:
d.items()

dict_items([('key1', 'item1'), ('key2', 'item2')])

In [81]:
lst = [1,2,3]

In [82]:
lst.pop()

3

In [108]:
lst

[1, 2]

In [83]:
'x' in [1,2,3]

False

In [84]:
'x' in ['x','y','z']

True



# =====================  PART - 2 ========================

# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

### Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: **vectors,arrays,matrices, and number generation**. Let's start by discussing arrays.

# 2.1 Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column)


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval. (same as seq() method in R)

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### zeros and ones

Generate arrays of zeros or ones

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [16]:
np.linspace(0,10,3)
# seq(0, 10, length.out = 3) as used in R 

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [37]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [19]:
np.random.rand(2)

array([0.4168594 , 0.16422106])

In [18]:
np.random.rand(5,5)

array([[0.33371118, 0.34319282, 0.72743529, 0.34876676, 0.96682784],
       [0.50934798, 0.55741392, 0.44898413, 0.9268689 , 0.99626748],
       [0.47303299, 0.22070455, 0.59786895, 0.47015036, 0.0581506 ],
       [0.14515479, 0.48025655, 0.25238249, 0.26587709, 0.83500126],
       [0.29003626, 0.47919666, 0.73504955, 0.25851799, 0.89794887]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(2)

array([-0.94830645,  0.80847746])

In [20]:
np.random.randn(5,5)

array([[ 0.56747593, -0.24927514, -0.19239578, -1.19321264, -2.16080915],
       [ 0.94410005,  0.38345592, -0.71832965,  0.22537232,  2.15568259],
       [-0.83998786,  0.23741113, -0.09165337,  0.48479975,  1.45805003],
       [-1.39779514,  0.1162762 ,  0.17916911,  0.23645086, -1.12615982],
       [ 1.72891056, -0.23289678,  0.75540383, -0.28040264,  0.35345829]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [26]:
np.random.randint(1,100)

8

In [30]:
np.random.randint(1,100,10)

array([13, 69, 34, 42, 25,  8, 91, 13, 48, 81])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [39]:
arr = np.arange(25)
ranarr = np.random.randint(0,25,10)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr

array([16, 11, 19, 18, 22,  6,  2, 12,  4, 15])

## Reshape
Returns an array containing the same data with a new shape.

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
ranarr.reshape(5,2)

array([[16, 11],
       [19, 18],
       [22,  6],
       [ 2, 12],
       [ 4, 15]])

In [47]:
ranarr

array([16, 11, 19, 18, 22,  6,  2, 12,  4, 15])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [59]:
ranarr

array([15,  4, 10, 23, 24, 24, 22, 23, 20,  9])

In [49]:
ranarr.max()
# max element

22

In [48]:
ranarr.argmax()
# argument to max element

4

In [62]:
ranarr.min()

4

In [63]:
ranarr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [56]:
# Vector
arr.shape

(25,)

In [60]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [62]:
arr.reshape(1,25).shape

(1, 25)

In [63]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### dtype

You can also grab the data type of the object in the array:

In [66]:
arr.dtype

dtype('int64')

# 2.2 NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic.(Same as in R)

In [67]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [70]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
# Warning on division by zero, but not an error!
# Just replaced with "nan"
arr/arr

/home/ideaplunge/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
# Also warning, but not an error instead infinity
1/arr

/home/ideaplunge/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [77]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [79]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
np.max(arr) #same as arr.max()

9

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [80]:
np.log(arr)

/home/ideaplunge/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# 2.3 NumPy Indexing and Selection

how to select elements or groups of elements from an array.

In [82]:
import numpy as np

In [136]:
#Creating sample array
arr = np.arange(0,11)

In [137]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [150]:
#Get a value at an index
arr[8]

8

In [151]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [152]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [153]:
# index starts at 0; dont forget that
arr[:4]

array([0, 1, 2, 3])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [154]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [155]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

changing the slice would also change the original array. (unlike R - this doesnt happen there)

In [158]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [98]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### copy
Data is not copied, it's a view of the original array! This avoids memory problems!

In [159]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

changes in copy wont affect the original array

In [160]:
arr_copy[:] = 0
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [161]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. comma notation is recommended for clarity.

In [162]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [163]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [115]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [119]:
# Getting individual element value
arr_2d[1,0]

20

In [130]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [117]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [148]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [171]:
# changing same as R 
arr_2d[2,:] = 0
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [ 0,  0,  0]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [173]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [185]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

10

In [186]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following (notice double brackets)

In [188]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [189]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size.

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [190]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [191]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [192]:
bool_arr = arr>4

In [193]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [194]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [195]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])



# =====================  PART - 3 ========================

# Pandas

* Series
* DataFrames
* Missing Data
* GroupBy
* Merging,Joining,and Concatenating
* Operations
* Data Input and Output

# 3.1 Series

The first main data type we will learn about for pandas is the Series data type. Let's import Pandas and explore the Series object.

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

Let's explore this concept through some examples:

In [196]:
import numpy as np
import pandas as pd

### Creating a Series

You can convert a list,numpy array, or dictionary to a Series:

In [197]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

** Using Lists**

In [198]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [200]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [201]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

** NumPy Arrays **

In [205]:
arr

array([10, 20, 30])

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [202]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

** Dictionary**

In [204]:
d

{'a': 10, 'b': 20, 'c': 30}

In [203]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types:

In [8]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [210]:
# Even functions (although unlikely that you will use this)
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

## Using an Index

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like a hash table or dictionary).

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [211]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                                   

In [212]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [208]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])                                   

In [209]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [14]:
ser1['USA']

1

Operations are then also done based off of index:

In [213]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

Let's stop here for now and move on to DataFrames, which will expand on the concept of Series!

# 3.2 DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index.

In [1]:
import pandas as pd
import numpy as np

In [3]:
from numpy.random import randn
np.random.seed(101)

In [4]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [7]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Selection and Indexing

various methods to grab data from a DataFrame

In [8]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [10]:
# Pass a list of column names - notice list ie []
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [12]:
# SQL Syntax (NOT RECOMMENDED!) - like R's $ 
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

DataFrame Columns are just Series

In [16]:
type(df['W'])

pandas.core.series.Series

**Creating a new column:** - feature engineering

In [17]:
df['new'] = df['W'] + df['Y']

In [18]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

** Removing Columns** - *axis =1 for column*

In [21]:
df.drop('new',axis=1) 

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [22]:
# Not inplace unless specified!
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [23]:
df.drop('new',axis=1,inplace=True)

In [24]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

Can also drop rows this way:

In [25]:
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [26]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

** Selecting Rows**

In [28]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

Or select based off of position instead of label 

In [199]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [30]:
df.iloc[0,0]

2.706849839399938

** Selecting subset of rows and columns **

In [48]:
df.loc['B','Y']

-0.8480769834036315

In [49]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [202]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [203]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [204]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [205]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [31]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

For two conditions you can use | and & with parenthesis:

In [52]:
df[(df['W']>0) & (df['Y'] > 1)]

W         X         Y         Z States
E  0.190794  1.978757  2.605967  0.683509     CO

In [56]:
df[(df['W']>0) & (df['Y'] > 1)][['W','X','States']]

W         X States
E  0.190794  1.978757     CO

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [59]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [60]:
# Reset to default 0,1...n index
df.reset_index()

index         W         X         Y         Z States
0     A  2.706850  0.628133  0.907969  0.503826     CA
1     B  0.651118 -0.319318 -0.848077  0.605965     NY
2     C -2.018168  0.740122  0.528813 -0.589001     WY
3     D  0.188695 -0.758872 -0.933237  0.955057     OR
4     E  0.190794  1.978757  2.605967  0.683509     CO

In [61]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [62]:
df['States'] = newind

In [63]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [64]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [65]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [66]:
df.set_index('States',inplace=True)

In [67]:
df

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [68]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [69]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [75]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1 -1.467514 -0.494095
   2 -0.162535  0.485809
   3  0.392489  0.221491
G2 1 -0.855196  1.541990
   2  0.666319 -0.538235
   3 -0.568581  1.407338

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [76]:
df.loc['G1']

A         B
1 -1.467514 -0.494095
2 -0.162535  0.485809
3  0.392489  0.221491

In [77]:
df.loc['G1'].loc[1]

A   -1.467514
B   -0.494095
Name: 1, dtype: float64

In [97]:
df.loc['G1'][['A']]

A
1 -1.467514
2 -0.162535
3  0.392489

In [98]:
df.index.names

FrozenList([None, None])

In [99]:
df.index.names = ['Group','Num']

In [100]:
df

A         B
Group Num                    
G1    1   -1.467514 -0.494095
      2   -0.162535  0.485809
      3    0.392489  0.221491
G2    1   -0.855196  1.541990
      2    0.666319 -0.538235
      3   -0.568581  1.407338

**.xs** - Returns a cross-section (row(s) or column(s)) from the Series/DataFrame. Defaults to cross-section on the rows (axis=0)

In [101]:
df.xs('G1')

A         B
Num                    
1   -1.467514 -0.494095
2   -0.162535  0.485809
3    0.392489  0.221491

In [102]:
df.xs(['G1',1])

A   -1.467514
B   -0.494095
Name: (G1, 1), dtype: float64

In [103]:
df.xs(1,level='Num')

A         B
Group                    
G1    -1.467514 -0.494095
G2    -0.855196  1.541990

# 3.3 Missing Data

Let's see a few convenient methods to deal with Missing Data in pandas

In [105]:
import numpy as np
import pandas as pd

In [106]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [107]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [108]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [13]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [109]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [111]:
# replacing NA 
df.fillna(value='FILL VALUE')

A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [113]:
# replacing NA 
df.fillna(value=-99)

A     B  C
0   1.0   5.0  1
1   2.0 -99.0  2
2 -99.0 -99.0  3

In [116]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# 3.4 Groupby

The groupby method allows you to group rows of data together and call aggregate functions

In [117]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [118]:
df = pd.DataFrame(data)

In [119]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

** Now you can use the .groupby() method to group rows together based off of a column name. For instance let's group based off of Company. This will create a DataFrameGroupBy object:**

In [122]:
df.groupby('Company')

You can save this object as a new variable:

In [123]:
by_comp = df.groupby("Company")

And then call aggregate methods off the object:

In [125]:
by_comp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [126]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

More examples of aggregate methods:

In [127]:
by_comp.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [39]:
by_comp.min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [154]:
by_comp.max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [155]:
by_comp.count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [135]:
by_comp.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [136]:
by_comp.describe().transpose()['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

# 3.5 Merging, Joining, and Concatenating

There are 3 main ways of combining DataFrames together: Merging, Joining and Concatenating. In this lecture we will discuss these 3 methods with examples.

### Example DataFrames

In [137]:
import pandas as pd

In [138]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [139]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [140]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [141]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [142]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [143]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

## Concatenation

Concatenation basically glues together DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use **pd.concat** and pass in a list of DataFrames to concatenate together:

In [144]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [146]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

_____
## Example DataFrames

In [170]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [148]:
left

A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3

In [149]:
right

C   D key
0  C0  D0  K0
1  C1  D1  K1
2  C2  D2  K2
3  C3  D3  K3

___

## Merging

The **merge** function allows you to merge DataFrames together using a similar logic as merging SQL Tables together. For example:

In [150]:
pd.merge(left,right,how='inner',on='key')

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

Or to show a more complicated example:

In [162]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                         'C': ['C0', 'C1', 'C2', 'C3'],
                         'D': ['D0', 'D1', 'D2', 'D3']})

In [161]:
pd.merge(left, right, on=['key1', 'key2'])

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [163]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

A    B key1 key2    C    D
0   A0   B0   K0   K0   C0   D0
1   A1   B1   K0   K1  NaN  NaN
2   A2   B2   K1   K0   C1   D1
3   A2   B2   K1   K0   C2   D2
4   A3   B3   K2   K1  NaN  NaN
5  NaN  NaN   K2   K0   C3   D3

In [41]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

A    B key1 key2   C   D
0   A0   B0   K0   K0  C0  D0
1   A2   B2   K1   K0  C1  D1
2   A2   B2   K1   K0  C2  D2
3  NaN  NaN   K2   K0  C3  D3

In [164]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A2  B2   K1   K0   C2   D2
4  A3  B3   K2   K1  NaN  NaN

## Joining
Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

In [166]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [167]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [168]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [169]:
left.join(right, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

_____

# 3.6 Operations

There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category. Let's show them here in this lecture:

In [172]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

### Info on Unique Values

In [174]:
# unique elements
df['col2'].unique()

array([444, 555, 666])

In [173]:
# number of unique elements
df['col2'].nunique()

3

In [176]:
# summary table - factor summary
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

### Selecting Data

In [177]:
#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [178]:
newdf

col1  col2 col3
3     4   444  xyz

### Applying Functions

In [179]:
def times2(x):
    return x*2

In [180]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [181]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [61]:
df['col1'].sum()

10

** Permanently Removing a Column**

In [182]:
del df['col1']

In [183]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

** Get column and index names: **

In [184]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [185]:
df.index

RangeIndex(start=0, stop=4, step=1)

** Sorting and Ordering a DataFrame:**

In [186]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [187]:
df.sort_values(by='col2') #inplace=False by default

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

** Find Null Values or Check for Null Values**

In [188]:
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [189]:
# Drop rows with NaN Values
df.dropna()

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

** Filling in NaN values with something else: **

In [190]:
import numpy as np

In [191]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [192]:
df.fillna('FILL')

col1  col2 col3
0     1  FILL  abc
1     2   555  def
2     3   666  ghi
3  FILL   444  xyz

In [193]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [194]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [200]:
# Pivot Tables
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

_______

# 3.7 Data Input and Output

This notebook is the reference code for getting input and output, pandas can read a variety of file types using its pd.read_ methods. Let's take a look at the most common data types:

In [205]:
import os
import numpy as np
import pandas as pd

## CSV

### CSV Input

In [207]:
df = pd.read_csv()

df

TypeError: parser_f() missing 1 required positional argument: 'filepath_or_buffer'

### CSV Output

In [204]:
df.to_csv('example',index=False)

## Excel
Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash. 

### Excel Input

In [35]:
pd.read_excel('Excel_Sample.xlsx',sheetname='Sheet1')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### Excel Output

In [33]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

## HTML

You may need to install htmllib5,lxml, and BeautifulSoup4. In your terminal/command prompt run:

    conda install lxml
    conda install html5lib
    conda install BeautifulSoup4

Then restart Jupyter Notebook.
(or use pip install if you aren't using the Anaconda Distribution)

Pandas can read table tabs off of html. For example:

### HTML Input

Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects:

In [5]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [7]:
df[0]

Bank Name             City  ST   CERT  \
0                        First CornerStone Bank  King of Prussia  PA  35312   
1                            Trust Company Bank          Memphis  TN   9956   
2                    North Milwaukee State Bank        Milwaukee  WI  20364   
3                        Hometown National Bank         Longview  WA  35156   
4                           The Bank of Georgia   Peachtree City  GA  35259   
5                                  Premier Bank           Denver  CO  34112   
6                                Edgebrook Bank          Chicago  IL  57772   
7                          Doral BankEn Espanol         San Juan  PR  32102   
8             Capitol City Bank & Trust Company          Atlanta  GA  33938   
9                       Highland Community Bank          Chicago  IL  20290   
10             First National Bank of Crestview        Crestview  FL  17557   
11                           Northern Star Bank          Mankato  MN  34983   
12       Frontier Bank, FSB D/B/A El Paseo Bank      Palm Desert  CA  34738   
13        The National Republic Bank of Chicago          Chicago  IL    916   
14                               NBRS Financial       Rising Sun  MD   4862   
15                        GreenChoice Bank, fsb          Chicago  IL  28462   
16                     Eastside Commercial Bank          Conyers  GA  58125   
17                       The Freedom State Bank          Freedom  OK  12483   
18                                  Valley Bank  Fort Lauderdale  FL  21793   
19                                  Valley Bank           Moline  IL  10450   
20                  Slavie Federal Savings Bank          Bel Air  MD  32368   
21                        Columbia Savings Bank       Cincinnati  OH  32284   
22                 AztecAmerica Bank En Espanol           Berwyn  IL  57866   
23                        Allendale County Bank          Fairfax  SC  15062   
24                           Vantage Point Bank          Horsham  PA  58531   
25        Millennium Bank, National Association         Sterling  VA  35096   
26                                 Syringa Bank            Boise  ID  34296   
27                            The Bank of Union          El Reno  OK  17967   
28                         DuPage National Bank     West Chicago  IL   5732   
29   Texas Community Bank, National Association    The Woodlands  TX  57431   
..                                          ...              ...  ..    ...   
515                           ANB Financial, NA      Bentonville  AR  33901   
516                                   Hume Bank             Hume  MO   1971   
517                      Douglass National Bank      Kansas City  MO  24660   
518                           Miami Valley Bank         Lakeview  OH  16848   
519                                     NetBank       Alpharetta  GA  32575   
520                   Metropolitan Savings Bank       Pittsburgh  PA  35353   
521                             Bank of Ephraim          Ephraim  UT   1249   
522                               Reliance Bank     White Plains  NY  26778   
523       Guaranty National Bank of Tallahassee      Tallahassee  FL  26838   
524                         Dollar Savings Bank           Newark  NJ  31330   
525                        Pulaski Savings Bank     Philadelphia  PA  27203   
526       First National Bank of Blanchardville   Blanchardville  WI  11639   
527                       Southern Pacific Bank         Torrance  CA  27094   
528                 Farmers Bank of Cheneyville      Cheneyville  LA  16445   
529                               Bank of Alamo            Alamo  TN   9961   
530        AmTrade International BankEn Espanol          Atlanta  GA  33784   
531              Universal Federal Savings Bank          Chicago  IL  29355   
532                Connecticut Bank of Commerce         Stamford  CT  19183   
533                            New Century Bank  Shelby Township  MI  34979   
534      

____

_____
_____
# SQL (Optional)

* Note: If you are completely unfamiliar with SQL you can check out my other course: "Complete SQL Bootcamp" to learn SQL.

The pandas.io.sql module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API. Database abstraction is provided by SQLAlchemy if installed. In addition you will need a driver library for your database. Examples of such drivers are psycopg2 for PostgreSQL or pymysql for MySQL. For SQLite this is included in Python’s standard library by default. You can find an overview of supported drivers for each SQL dialect in the SQLAlchemy docs.


If SQLAlchemy is not installed, a fallback is only provided for sqlite (and for mysql for backwards compatibility, but this is deprecated and will be removed in a future version). This mode requires a Python database adapter which respect the Python DB-API.

See also some cookbook examples for some advanced strategies.

The key functions are:

* read_sql_table(table_name, con[, schema, ...])	
    * Read SQL database table into a DataFrame.
* read_sql_query(sql, con[, index_col, ...])	
    * Read SQL query into a DataFrame.
* read_sql(sql, con[, index_col, ...])	
    * Read SQL query or database table into a DataFrame.
* DataFrame.to_sql(name, con[, flavor, ...])	
    * Write records stored in a DataFrame to a SQL database.

In [36]:
from sqlalchemy import create_engine

In [37]:
engine = create_engine('sqlite:///:memory:')

In [40]:
df.to_sql('data', engine)

In [42]:
sql_df = pd.read_sql('data',con=engine)

In [43]:
sql_df

index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15

# Great Job!